---
title: "Work"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(manipulate)
```

```{r}
vb1 <- read_csv("C:/Users/kayag/Downloads/Volleyball stats_ 2021 - AGGREGATE (7).csv")
View(Volleyball_stats_2021_AGGREGATE_4_)

saveRDS(vb, file="~/Vb-Work/vb1.rds")

library(dplyr)

vb <- readRDS(file="~/Vb-Work/vb1.rds")

view(vb)

## Dig to kill work

vb %>%
  group_by(dig) %>%
  summarise(count=n())

#about 37% of our hits come off of a dig (when the other team attacks the ball, including setter dumps). 747 counted digs. 

vb %>%
  group_by(dig, hit) %>%
  summarise(all=n())

#Given that a ball was dug, based off of these stats, 15% chance it will be an error. 52% chance it will be an attempt. 32% it will be a kill. Compare this to when a ball is not dug: 18% chance it will be an error. 45% chance it will be an attempt. 37% chance it will be a kill. Not too far off?

vb %>% 
  filter(dig==0) %>% 
  mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
  group_by(opponent, set, result) %>% 
  summarise(eff=(sum(kill.c)-sum(error.c))/n()) %>% 
  mutate(kill.t=eff>.4,
         win=result==1)  %>% 
  ggplot(aes(x=kill.t, fill=win)) +
  geom_bar(position="fill")


m<-vb %>% 
  filter(dig==0) %>% 
  mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
  group_by(opponent, set) %>% 
  summarise(eff=(sum(kill.c)-sum(error.c))/n())

mean(m$eff)

#mean dig to kill efficiency: .179
#mean non-dig to kill efficiency: .205

vb %>% 
  filter(dig==0) %>% 
  mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
  group_by(opponent, set, result) %>% 
  summarise(eff=(sum(kill.c)-sum(error.c))/n()) %>% 
  mutate(win=result==1) %>% 
    ggplot(aes(x=eff, fill=win)) +
    geom_histogram(bins=13, colour="white")




vb %>% 
  filter(dig==0) %>% 
  mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
  group_by(opponent, set, result) %>% 
  summarise(eff=(sum(kill.c)-sum(error.c))/n()) %>% 
  mutate(tophit=ifelse(eff>.3, ">.3", "<.3"),
         win=result==1) %>% 
    ggplot(aes(x=tophit, fill=win)) +
    geom_bar(position="fill") + labs(x="Hitting efficiency") + scale_fill_manual("legend", values = c("TRUE" = "orange3", "FALSE" = "black")) + theme(text = element_text(size=30))

# non digs: HIGH POSITIVE CORRELATION HERE. Can definitely see that higher hitting off non-digs efficiency directly corresponds to wins. Threshold: .3. 11 sets where, off of non-digs, we hit above .3. We won all but one of those (Fun fact: this one game was one where ).

#lmao. uwo set 1:
vb %>% 
  filter(opponent=="uwo", set==1) %>% 
  ggplot(aes(x=points.total, y=points.position)) +
  geom_point() +
  geom_smooth()


vb %>% 
  filter(dig==1) %>% 
  mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
  group_by(opponent, set, result) %>% 
  summarise(eff=(sum(kill.c)-sum(error.c))/n()) %>% 
  mutate(hitting.efficiency=ifelse(eff<.1, "<.2", ">.2"),
         win=result==1) %>% 
    ggplot(aes(x=hitting.efficiency, fill=win)) +
    geom_bar()

vb %>% 
  filter(dig==1) %>% 
  mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
  group_by(opponent, set, result) %>% 
  summarise(eff=(sum(kill.c)-sum(error.c))/n()) %>% 
  mutate(hitting.efficiency=ifelse(eff<.05, "<.2", ">.2"),
         win=result==1) %>% 
  ggplot(aes(x=hitting.efficiency, fill=win)) +
    geom_bar()
  

#not a super linear relatioship, but there is definitely evidence that higher dig to kill hitting efficiency yields a better chance of winning. If we hit over .2 off of our kills, we have a roughly 65% chace of winning. On the other hand, if we hit less than a .2 off of our digs, 






##OSS

vb %>% 
  filter(oss==1) %>% 
  mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
  group_by(opponent, set, result) %>% 
  summarise(eff=(sum(kill.c)-sum(error.c))/n()) %>% 
  mutate(win=result==1) %>% 
    ggplot(aes(x=eff, fill=win)) +
    geom_histogram(bins=12, colour="white")



vb %>%
  mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
  group_by(opponent, set, oss) %>% 
  summarise(eff=(sum(kill.c)-sum(error.c))/n()) %>% 
  mutate(oss1=oss==1) %>% 
    ggplot(aes(x=eff, fill=oss1)) +
    geom_histogram(bins=12, colour="white")

vb %>%
  filter(oss==1) %>% 
  mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
  group_by(opponent, set) %>% 
  summarise(eff=(sum(kill.c)-sum(error.c))/n()) %>%
    ggplot(aes(x=eff)) +
    geom_histogram(bins=12, colour="white") + theme(text = element_text(size=30)) + labs(x="Hitting efficiency")


vb %>% 
  filter(oss==1, hit=="kill")

(624-302)/(624+302+810)
(95-41)/(95+41+164)


vb %>% 
  filter(oss==1) %>% 
  mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
  group_by(opponent, set, result) %>% 
  summarise(eff=(sum(kill.c)-sum(error.c))/n()) %>% 
  mutate(tophit=ifelse(eff>.4, ">.39", "<.39"),
         win=result==1) %>% 
    ggplot(aes(x=tophit, fill=win)) +
    geom_bar(position="fill")



mean(m$eff)



vb$hit <- factor(vb$hit, levels = c("error", "attempt", "kill"))

ggplot(vb) +
  geom_bar(aes(x=dig, fill=hit), position="fill") + scale_fill_manual("legend", values = c("kill" = "orange3", "attempt" = "gray100", "error" = "black"))

ggplot(vb) +
  geom_bar(aes(x=oss, fill=hit), position="fill") + scale_fill_manual("legend", values = c("kill" = "orange3", "attempt" = "gray100", "error" = "black"))





#ordinal regression attempts
m <- polr(as.factor(hit2) ~ dig + set + points.total, data = vb2, Hess=TRUE)

summary(m)

summary(as.factor(vb2$hit2))

vb3$hit <- factor(vb3$hit, levels = c("error", "attempt", "kill"))

summary(vb$hit2)





## points total vs. avg points position
vb %>% 
  group_by(points.total) %>% 
  summarise(average.pt.position=mean(points.position)) %>% 
  ggplot() +
  geom_point(aes(x=points.total, y=average.pt.position)) +
  ylim(-5,4) +
  geom_smooth(aes(x=points.total, y=average.pt.position), span=.2) +
    theme(text = element_text(size=30)) + labs(x="Total Points", y="Avg. Point Difference") +
  geom_hline(aes(yintercept = 0), color="black")

mean(vb3$points.position)


#Pt position vs set
vb %>% 
  group_by(set) %>% 
  summarise(average.pt.position=mean(points.position)) %>% 
  ggplot() +
  geom_point(aes(x=set, y=average.pt.position)) +
  ylim(-5,4) + theme(text = element_text(size=30)) + labs(x="Set #", y="Avg. Point Difference") +
  geom_hline(aes(yintercept = 0), color="black") + geom_smooth(aes(x=set, y=average.pt.position), span=1)




#calculating hitting efficiency
vb %>% 
  mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
  group_by(opponent, set, result) %>% 
  summarise(eff=(sum(kill.c)-sum(error.c))/n()) %>% 
  mutate(tophit=eff>.31,
         win=result==1) %>% 
  ggplot(aes(x=tophit, fill=win)) +
  geom_bar(position="fill") + scale_fill_manual("win", values = c("FALSE" = "orange3", "TRUE" = "gray100")) + theme(text = element_text(size=30)) +labs(x="Hitting efficiency > .31")

# 12 sets where we hit above a .31. We won every. single. one. of these games (against, yes macalester and westminster, but also aurora and dubuque, and hamline). 100% chance of winning if team hitting efficiency is above .31

m$eff

# %>% 
#   ggplot() +
# geom_bar(mapping = aes(x = result, fill = eff<.3), position = "fill")


k<-vb %>% 
  filter(oss==0|oss==1) %>% 
  mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
  mutate(eff=(sum(kill.c)-sum(error.c))/n())

k$eff
```


```{r}
#EDA

vb %>% 
  group_by(set, opponent)
  filter(set==5)

count(vb)

ggplot(data = vb, aes(hit)) +
  geom_histogram(stat = "count", fill="darkgoldenrod2") +
    theme(text = element_text(size=32))

filter(vb, hit=="error")

(719-343)/(719+984+343)

ggplot(data = vb) +
  geom_bar(aes(oss, fill = as.character(hit)), position = "fill")

ggplot(data = vb, aes(dig, fill = hit)) +
  geom_histogram(stat = "count", position="fill") + scale_fill_manual("legend", values = c("kill" = "orange3", "attempt" = "gray100", "error" = "black")) + theme(text = element_text(size=30))


ggplot(data = vb) +
  geom_bar(aes(oss, fill = as.character(hit)), position = "fill") + scale_fill_manual("legend", values = c("kill" = "orange3", "attempt" = "gray100", "error" = "black")) + theme(text = element_text(size=30))

vb %>% group_by(dig) %>% summarise(n())


vb.lm <- lm(hit ~ dig, data = vb)
summary(vb.lm)

ggplot(data = vb, aes(points.position)) +
  geom_histogram()

ggplot(data = vb, aes(x = points.total, y = mean(points.position))) +
  geom_point()

vb %>% group_by(set) %>% 
  summarise(n(set))

vb %>% group_by(hit) %>% 
  summarise(n())

vb2 <- vb %>% group_by(hit, set) %>% 
  summarise(n())

vb2 <- vb2 %>% rename(hit.n = 'n()')

vb2
```



```{r}
vb <- read_csv("C:/Users/kayag/Downloads/Volleyball stats_ 2021 - AGGREGATE (7).csv")
View(Volleyball_stats_2021_AGGREGATE_4_)

saveRDS(vb, file="~/Vb-Work/vb.rds")

library(dplyr)

#oss

vb$hit <- factor(vb3$hit, levels = c("error", "attempt", "kill"))

ggplot(data = vb) +
  geom_bar(aes(oss, fill = as.character(hit)), position = "fill") + scale_fill_manual("legend", values = c("kill" = "orange3", "attempt" = "gray100", "error" = "black")) + theme(text = element_text(size=30))

## Dig to kill work

vb %>%
  group_by(dig) %>%
  summarise(count=n())

#about 37% of our hits come off of a dig (when the other team attacks the ball, including setter dumps). 747 counted digs. 

vb %>%
  group_by(dig, hit) %>%
  summarise(all=n())

#Given that a ball was dug, based off of these stats, 15% chance it will be an error. 52% chance it will be an attempt. 32% it will be a kill. Compare this to when a ball is not dug: 18% chance it will be an error. 45% chance it will be an attempt. 37% chance it will be a kill. Not too far off?

# try to see if there is a threshold (when we win, what is our dig to kill?)

vb3$hit <- factor(vb3$hit, levels = c("error", "attempt", "kill"))

ggplot(vb3) +
  geom_bar(aes(x=dig, fill=hit), position="fill") + scale_fill_manual("legend", values = c("kill" = "orange3", "attempt" = "gray100", "error" = "black"))


vb %>% 
  filter(hit=="kill") %>% 
  group_by(result) %>% 
  summarise(kill.count=n())

vb %>% 
  group_by(result) %>% 
  summarise(kill.count=count(vb,hit=="kill"))

vb %>% 
  count(hit, result) %>%
  group_by(result) %>%
  mutate(prop = n / sum(n)) %>%
  ggplot(mapping = aes(x = result, y = hit)) +
  geom_tile(mapping = aes(fill = prop))

ggplot(data = vb) +
  geom_count(mapping = aes(x = hit, y = result))


vb %>%
  group_by(result) %>% 
  summarise(kill.count=count(vb,hit=="kill"))


m<-vb %>% 
  group_by(opponent) %>% 
  summarise(kill.c=n(vb, hit=="kill"),
            attempt.c=count(vb, hit=="attempt"),
            error.c=count(vb, hit=="error"),
            eff=kill.c-error.c/(kill.c+attempt.c+error.c))




m$kill.c
m %>% filter(eff>.32)
summary(m)
ggplot(m) +
  geom_boxplot(aes(x=result), y=kill.c)




sum(with(vb,hit == "kill"))
count(filter(vb, hit=="kill"))


n<-vb %>% 
  filter(result==0)

count(n)

# dig to kill efficiency for games we won: 40%
# dig to kill efficiency for games we lost: 31%

# ordinal regression stuffs
m <- polr(as.factor(hit2) ~ dig + set + points.total, data = vb2, Hess=TRUE)

summary(m)

summary(as.factor(vb2$hit2))



summary(vb$hit2)

## points total vs. avg points position
vb3 %>% 
  group_by(points.total) %>% 
  summarise(average.pt.position=mean(points.position)) %>% 
  ggplot() +
  geom_point(aes(x=points.total, y=average.pt.position)) +
  ylim(-5,4) +
  geom_hline(aes(yintercept = 0), color="black") +
  geom_smooth(aes(x=points.total, y=average.pt.position), span=.2)

mean(vb3$points.position)

x<-c(1,5)
y<-c(0,0)

size(x)

#Pt position vs set
vb3 %>% 
  group_by(set) %>% 
  summarise(average.pt.position=mean(points.position)) %>% 
  ggplot() +
  geom_point(aes(x=set, y=average.pt.position)) +
  ylim(-5,4) +
  geom_hline(aes(yintercept = 0), color="black") + geom_smooth(aes(x=set, y=average.pt.position), span=1)






ggplot(data = vb3, mapping = aes(x = hit, y = points.position)) + geom_boxplot() 

summary(vb3$hits)


#hitters work


ggplot(vb) +
  geom_bar(aes(x=hit, fill=hitter), position="fill")

vb %>% filter(hitter=="gully", hit=="kill")

vb %>% 
  filter(points.position>= -5 & points.position<=5) %>% 
  ggplot() +
  geom_bar(aes(x=hitter, fill=hit), position="fill")

vb %>% 
  filter(points.position>5, hitter=="kate", hit=="error")


# When we are down by a lot (more than 5): Nic is your gal to set. Then nora. Then prolly any.
# 
# When we are up by a lot (more than 5): hehe mandy is your gal to set ;). Middles. Nic has highest kill %, but shockingly kate has not had a single error when we are above 5 pts! Then maybe gully.
# 
# If we are between -5 and 5: kate, gully


# By set:


vb %>% 
  filter(set==4) %>% 
  ggplot() +
  geom_bar(aes(x=hitter, fill=hit), position="fill")

# Set 1:
# middles (kate, then nic). oddly, cat tends to make quiiite a few errors in the first set. After middles, then gully.
# 
# Set 2: same as above, hitters generally kick it up. T hit negative.
# 
# Set 3: MANDY. hehe. Any has highest here, then nic, then kate. Also note: WOW hitting efficinecy doubles(ish) for a lot of players
# 
# Set 4: Very evenly matched. 
# 
# Set 5: any. nic

#Throughout a game:
  vb %>%
  filter(points.total>= 50 & points.position<=60) %>%
  ggplot() +
  geom_bar(aes(x=hitter, fill=hit), position="fill")
#   
# 0-10: kate, nic, gully
# 
# 10-20: kate, nic, gully
# 
# 20-30: kate, nic, gully
# 
# 30-40: kate, gully, any
# 
# 40-50: kate, nic
# 
# 50-60: nora. okay not useful data

vb %>% 
  filter(set==1) %>% 
  ggplot() +
  geom_bar(aes(x=hitter, fill=hit), position="fill")

vb %>%
  filter(oss==1) %>% 
  mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
  group_by(opponent, set) %>% 
  summarise(eff=(sum(kill.c)-sum(error.c))/n()) %>%
    ggplot(aes(x=eff)) +
    geom_histogram(bins=12, colour="white") + theme(text = element_text(size=20)) + labs(x="Hitting efficiency")


##error percent throughout a set


vb %>%
  filter(hitter=="gully"|hitter=="kate"|hitter=="t"|hitter=="any"|hitter=="cat"|hitter=="nic"|hitter=="nora") %>% 
  mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
  group_by(hitter, points.total) %>% 
  summarise(eff=(sum(error.c))/n()) %>%
    ggplot(aes(x=points.total, y=eff, color=hitter)) +
    geom_smooth(se=F) + theme(text = element_text(size=30)) + labs(x="Total points", y="Error %", main="Overall")

vb %>% 
  filter(oss==1|oss==0)

 vb %>% 
   filter(dig==1) %>% 
   mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
   group_by(hitter) %>% 
   summarise(eff=(sum(kill.c)-sum(error.c))/n())
 
 
 
187036 +195685 +289335 +234427+183139+170265+96577+116640+194042

```


#Let's try to make a manipulate graph

```{r}



#create slider for a and b
manipulate({
  modelSoln = tumorV(c(a=a,b=b), t_data, V0, K0)  # Solve tumor model
  plot(t_data,V_data)  # Plot data
  lines(modelSoln$t,modelSoln$V,type="l",ylab="V")  # Overlay model output on data
},
a=slider(0,2,step=0.1),
b=slider(0,2,step=0.1)
)
```


#make a model from toal points and difference. then graph total points vs hit % with the slider parameter being 

#turn point difference into categorical, plot a series of graphs (facet wraps)

#hitters as random effects
