---
title: "Modeling"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(dplyr)
library(tidyverse)

vb <- read_csv(file="Vbstats.2021.csv")
```

```{r}
view(vb)
vb1 <- vb %>%
  group_by(set) %>% 
  mutate(pointgroup = cut_number(points.total, 8), kill.c=ifelse(hit=="kill", 1, 0), error.c=ifelse(hit=="error", 1, 0))
  
vb1 <- vb1 %>% 
  group_by(pointgroup) %>% 
  mutate(hit.eff = (sum(kill.c)-sum(error.c))/n())

vb2 <- vb1 %>% 
  group_by(set) %>% 
  mutate(hit.eff = (sum(kill.c)-sum(error.c))/n())

view(vb1)
  

#   group_by() %>%
#   summarize(mean = mean(matings), variance = var(matings), n = n(), ratio = variance/mean) 
# 
# vb %>%
#   filter(oss==1) %>% 
#   mutate(kill.c=ifelse(hit=="kill", 1, 0),
#          error.c=ifelse(hit=="error", 1, 0)) %>% 
#   group_by(opponent, set) %>% 
#   summarise(eff=(sum(kill.c)-sum(error.c))/n()) %>%
#     ggplot(aes(x=eff)) +
#     geom_histogram(bins=12, colour="white") + theme(text = element_text(size=20)) + labs(x="Hitting efficiency")
```


# Linear regression attempt

```{r}
vb %>%
  mutate(kill.c=ifelse(hit=="kill", 1, 0),
         error.c=ifelse(hit=="error", 1, 0)) %>% 
  group_by(points.total) %>% 
  summarise(k=(sum(error.c))) %>%
    ggplot() +
    geom_density(aes(x=points.total, y=k))

vb %>% 
  filter(points.total<=10)

ggplot(vb1, aes(hit.eff)) + 
  geom_histogram()

class(vb1$hit.eff)

model1 <- lm(hit.eff ~ 1, data = vb1)
summary(model1)

model2 <- lm(hit.eff ~ set + points.position + points.total + oss + dig + result, data = vb1)
summary(model2)

model3 <- lm(hit.eff ~ points.position + points.total + oss + dig + result, data = vb2)
summary(model2)

# consider grouping the other predictors too
```

```{r}
library(tidymodels)

```




```{r}
# modeling

vb$hit = factor(vb$hit, levels = c("error", "attempt", "kill"), ordered = TRUE)

m <- polr(hit ~ points.total + points.position + set + oss + dig + hitter, data = vb, Hess=TRUE)

summary(m) # only significant predictor is points.total

(ctable <- coef(summary(m)))

p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2

(ctable <- cbind(ctable, "p value" = p))


```

